### ISSUE TITLE
Great project - shame about the name!

### ISSUE THREAD

**Issue by joelmoss** [amatsuda/wanko#2]
I'm assuming here that you are not aware of the mostly British slang word - [Wank](http://www.urbandictionary.com/define.php?term=wank), but whether you do or not, you may want to rethink the name of the project ;)

**Comment by amatsuda** [comment]
@joelmoss Thank you very much for the advice! I kind of do know the word, and yes, I'm seriously planning to rename as soon as I come up with a new name ;)

**Comment by yui-knk** [comment]
I think we can close this issue because name was changed :)
